const SETMAINUSER = 'SETMAINUSER';
const SETUSERS = 'SETUSERS';
const SETVIDEOS = 'SETVIDEOS';
const SETSERVICES = 'SETSERVICES';

export default {
    SETMAINUSER,
    SETUSERS,
    SETVIDEOS,
    SETSERVICES
};
